/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BeeminderSyncPlugin,
  insertBeeminderMarker: () => insertBeeminderMarker
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/beeminder-api.ts
var import_obsidian = require("obsidian");
var BASE_URL = "https://www.beeminder.com/api/v1";
var BeeminderApi = class {
  constructor(getToken) {
    this.getToken = getToken;
  }
  async request(path, options = {}) {
    var _a;
    const token = await this.getToken();
    if (!token) {
      throw new Error("Missing Beeminder auth token.");
    }
    const url = new URL(`${BASE_URL}${path}`);
    url.searchParams.set("auth_token", token);
    const resp = await (0, import_obsidian.requestUrl)({
      url: url.toString(),
      method: (_a = options.method) != null ? _a : "GET",
      body: options.body,
      contentType: options.contentType
    });
    if (resp.status >= 400) {
      const error = typeof resp.json === "object" && resp.json && "errors" in resp.json ? String(resp.json.errors) : resp.text;
      throw new Error(error || `Beeminder API returned ${resp.status}`);
    }
    return resp.json;
  }
  async getUser() {
    return this.request("/users/me.json");
  }
  async getGoals(username) {
    return this.request(`/users/${encodeURIComponent(username)}/goals.json`);
  }
  async getGoalSlugs(username) {
    const goals = await this.getGoals(username);
    return goals.map((g) => g.slug);
  }
  async createDatapoint(username, goalSlug, datapoint) {
    const params = new URLSearchParams({
      value: String(datapoint.value)
    });
    if (datapoint.comment)
      params.set("comment", datapoint.comment);
    if (datapoint.daystamp)
      params.set("daystamp", datapoint.daystamp);
    if (datapoint.requestid)
      params.set("requestid", datapoint.requestid);
    const resp = await this.request(
      `/users/${encodeURIComponent(username)}/goals/${encodeURIComponent(goalSlug)}/datapoints.json`,
      {
        method: "POST",
        body: params.toString(),
        contentType: "application/x-www-form-urlencoded"
      }
    );
    return resp.id;
  }
  async deleteDatapoint(username, goalSlug, datapointId) {
    await this.request(
      `/users/${encodeURIComponent(username)}/goals/${encodeURIComponent(goalSlug)}/datapoints/${encodeURIComponent(datapointId)}.json`,
      { method: "DELETE" }
    );
  }
};

// src/suggest.ts
var import_obsidian2 = require("obsidian");
var TASK_LINE_REGEX = /^(\s*)([-*+]|\d+[.)]) \[([^\]])\]\s+(.*)$/u;
var UNFILTERED_QUERIES = /* @__PURE__ */ new Set(["", "b", "be", "bee", "beem", "beemi", "beemin", "beemind", "beeminde", "beeminder", "goal", "\u{1F41D}"]);
var BeeminderSuggest = class extends import_obsidian2.EditorSuggest {
  constructor(plugin) {
    super(plugin.app);
    this.plugin = plugin;
  }
  onTrigger(cursor, editor, _file) {
    var _a;
    const line = editor.getLine(cursor.line);
    if (!TASK_LINE_REGEX.test(line))
      return null;
    const textUpToCursor = line.slice(0, cursor.ch);
    const wordMatch = textUpToCursor.match(/(?:^|\s)([^\s]*)$/u);
    const query = (_a = wordMatch == null ? void 0 : wordMatch[1]) != null ? _a : "";
    const queryStart = cursor.ch - query.length;
    const existingMarkerIndex = line.indexOf("\u{1F41D}");
    if (existingMarkerIndex !== -1 && existingMarkerIndex !== queryStart) {
      return null;
    }
    const minMatchLength = this.plugin.settings.autocompleteMinMatchLength;
    const lowerQuery = query.toLowerCase();
    const isTrigger = query.startsWith("\u{1F41D}") || query.length >= minMatchLength && (query.length === 0 || "beeminder".startsWith(lowerQuery) && lowerQuery.startsWith("b") || lowerQuery === "goal");
    if (!isTrigger)
      return null;
    return {
      start: { line: cursor.line, ch: cursor.ch - query.length },
      end: cursor,
      query
    };
  }
  getSuggestions(context) {
    const goals = this.plugin.settings.cachedGoals;
    const normalizedQuery = context.query.toLowerCase().replace(/^🐝\s*/, "").trim();
    const shouldFilter = !UNFILTERED_QUERIES.has(context.query.toLowerCase()) && normalizedQuery.length > 0;
    const goalSuggestions = goals.filter((goal) => {
      var _a;
      if (!shouldFilter)
        return true;
      const haystack = `${goal.slug} ${(_a = goal.title) != null ? _a : ""}`.toLowerCase();
      return haystack.includes(normalizedQuery);
    }).slice(0, 8).map((goal) => ({
      label: `\u{1F41D} ${goal.slug}`,
      insertText: `\u{1F41D} ${goal.slug}`
    }));
    return [
      { label: "\u{1F41D} Beeminder (custom)", insertText: "\u{1F41D} goal=1" },
      ...goalSuggestions
    ];
  }
  renderSuggestion(suggestion, el) {
    el.setText(suggestion.label);
  }
  selectSuggestion(suggestion, _evt) {
    if (!this.context)
      return;
    const { editor, start, end } = this.context;
    const line = editor.getLine(start.line);
    const replaced = line.slice(0, start.ch) + line.slice(end.ch);
    const updatedLine = insertBeeminderMarker(replaced.trimEnd(), suggestion.insertText);
    editor.replaceRange(
      updatedLine,
      { line: start.line, ch: 0 },
      { line: start.line, ch: line.length }
    );
    this.close();
  }
};

// src/main.ts
var BEE_REGEX = /🐝\s+(\S+?)(?:=(\d+(?:\.\d+)?))?(?:\s|$)/;
var TASK_LINE_REGEX2 = /^(\s*)([-*+]|\d+[.)]) \[([^\]])\]\s+(.*)$/u;
var TASKS_TRAILING_METADATA_REGEX = /\s(?=(?:#\S+|(?:🔺|⏫|🔼|🔽|⏬|🛫|➕|⏳|📅|✅|❌|🔁|🏁|⛔|🆔)\b))/u;
var DEFAULT_SETTINGS = {
  username: "",
  tokenStorageKey: "beeminder-auth-token",
  cachedGoals: [],
  autocompleteMinMatchLength: 1,
  showNotifications: true,
  syncedDatapoints: {}
};
var USAGE_TIPS = [
  {
    title: "Basic",
    body: "Add a \u{1F41D} annotation to any task to send a datapoint when that task is completed.",
    code: "- [ ] Read chapter 5 \u{1F41D} reading"
  },
  {
    title: "Custom value",
    body: "Use =number to send a custom value instead of the default +1.",
    code: "- [ ] Run 5km \u{1F41D} exercise=5"
  },
  {
    title: "With Tasks metadata",
    body: "Place \u{1F41D} before trailing Tasks metadata so the annotation is parsed correctly.",
    code: "- [ ] Write post \u{1F41D} words=500 \u{1F4C5} 2026-04-10"
  },
  {
    title: "Autocomplete",
    body: 'Type "\u{1F41D}", "bee", or "goal" on a task line to get suggestions from your cached goals.'
  },
  {
    title: "Unsync",
    body: "Unchecking a synced task removes the corresponding datapoint from Beeminder."
  }
];
function parseTaskLine(line, lineNumber) {
  const match = line.match(TASK_LINE_REGEX2);
  if (!match)
    return null;
  const status = match[3];
  const content = match[4];
  const beeMatch = content.match(BEE_REGEX);
  return {
    lineNumber,
    line,
    isDone: status.toLowerCase() === "x",
    goalSlug: beeMatch ? beeMatch[1] : null,
    value: (beeMatch == null ? void 0 : beeMatch[2]) ? parseFloat(beeMatch[2]) : 1
  };
}
function buildSnapshot(content) {
  const lines = content.split("\n");
  const tasks = /* @__PURE__ */ new Map();
  lines.forEach((line, i) => {
    const parsed = parseTaskLine(line, i);
    if (parsed)
      tasks.set(i, parsed);
  });
  return { tasks };
}
function buildTaskIdentity(task) {
  return JSON.stringify({
    line: task.line,
    isDone: task.isDone,
    goalSlug: task.goalSlug,
    value: task.value
  });
}
function insertBeeminderMarker(line, markerText) {
  if (line.includes("\u{1F41D}"))
    return line;
  const match = line.match(TASKS_TRAILING_METADATA_REGEX);
  if (!match || match.index === void 0) {
    return `${line} ${markerText}`;
  }
  return `${line.slice(0, match.index)} ${markerText}${line.slice(match.index)}`;
}
var BeeminderSyncPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.api = new BeeminderApi(() => this.getToken());
    this.fileSnapshots = /* @__PURE__ */ new Map();
  }
  async onload() {
    await this.loadSettings();
    this.registerEditorSuggest(new BeeminderSuggest(this));
    this.addSettingTab(new BeeminderSyncSettingTab(this.app, this));
    await this.captureInitialSnapshots();
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian3.TFile && file.extension === "md") {
          this.handleFileModify(file);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (file instanceof import_obsidian3.TFile) {
          const prev = this.fileSnapshots.get(oldPath);
          this.fileSnapshots.delete(oldPath);
          if (prev)
            this.fileSnapshots.set(file.path, prev);
          this.migrateSyncKeysForRename(oldPath, file.path);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file instanceof import_obsidian3.TFile) {
          this.fileSnapshots.delete(file.path);
          this.removeSyncKeysForFile(file.path);
        }
      })
    );
    this.addCommand({
      id: "insert-beeminder-marker",
      name: "Insert Beeminder marker on current task",
      editorCallback: (editor) => {
        var _a, _b;
        const lineNumber = editor.getCursor().line;
        const line = editor.getLine(lineNumber);
        if (!TASK_LINE_REGEX2.test(line)) {
          new import_obsidian3.Notice("Cursor must be on a task line.");
          return;
        }
        if (line.includes("\u{1F41D}")) {
          new import_obsidian3.Notice("This task already has a Beeminder marker.");
          return;
        }
        const goalSlug = (_b = (_a = this.settings.cachedGoals[0]) == null ? void 0 : _a.slug) != null ? _b : "goal";
        const updated = insertBeeminderMarker(line, `\u{1F41D} ${goalSlug}`);
        editor.replaceRange(updated, { line: lineNumber, ch: 0 }, { line: lineNumber, ch: line.length });
      }
    });
    this.addCommand({
      id: "refresh-beeminder-goals",
      name: "Refresh Beeminder goals",
      callback: async () => {
        await this.validateAndRefreshGoals();
        new import_obsidian3.Notice("Beeminder goals refreshed");
      }
    });
  }
  onunload() {
    this.fileSnapshots.clear();
  }
  // --- Token storage (secret storage with localStorage fallback) ---
  async storeToken(token) {
    if (this.app.secretStorage) {
      this.app.secretStorage.setSecret(this.settings.tokenStorageKey, token);
      return;
    }
    this.app.saveLocalStorage(this.getLegacyTokenKey(), token);
  }
  async clearToken() {
    if (this.app.secretStorage) {
      this.app.secretStorage.setSecret(this.settings.tokenStorageKey, "");
    }
    this.app.saveLocalStorage(this.getLegacyTokenKey(), null);
  }
  async getToken() {
    if (this.app.secretStorage) {
      const token = this.app.secretStorage.getSecret(this.settings.tokenStorageKey);
      if (token)
        return token;
    }
    return this.app.loadLocalStorage(this.getLegacyTokenKey());
  }
  getLegacyTokenKey() {
    return `${this.manifest.id}:${this.settings.tokenStorageKey}`;
  }
  // --- Goal management ---
  async validateAndRefreshGoals() {
    const user = await this.api.getUser();
    this.settings.username = user.username;
    this.settings.cachedGoals = (await this.api.getGoals(user.username)).map(
      (g) => ({ slug: g.slug, title: g.title })
    );
    await this.saveSettings();
  }
  // --- Snapshot management ---
  async captureInitialSnapshots() {
    const files = this.app.vault.getMarkdownFiles();
    await Promise.all(
      files.map(async (file) => {
        try {
          const content = await this.app.vault.cachedRead(file);
          this.fileSnapshots.set(file.path, buildSnapshot(content));
        } catch (e) {
        }
      })
    );
  }
  // --- File modification handling ---
  async handleFileModify(file) {
    const content = await this.app.vault.cachedRead(file);
    const currentSnapshot = buildSnapshot(content);
    const previousSnapshot = this.fileSnapshots.get(file.path);
    this.fileSnapshots.set(file.path, currentSnapshot);
    if (!previousSnapshot)
      return;
    const { unmatchedPreviousTasks, unmatchedCurrentTasks } = await this.migrateSyncKeysForMovedTasks(
      file.path,
      previousSnapshot,
      currentSnapshot
    );
    for (const prevTask of unmatchedPreviousTasks) {
      if (!prevTask.goalSlug || !prevTask.isDone)
        continue;
      await this.undoTaskCompletion(file, prevTask);
    }
    for (const currentTask of unmatchedCurrentTasks) {
      if (!currentTask.goalSlug || !currentTask.isDone)
        continue;
      await this.syncTaskCompletion(file, currentTask);
    }
  }
  async syncTaskCompletion(file, task) {
    if (!this.settings.username) {
      new import_obsidian3.Notice("Beeminder: Validate your token in settings before syncing.");
      return;
    }
    const syncKey = this.buildSyncKey(file.path, task.lineNumber, task.line);
    if (this.settings.syncedDatapoints[syncKey])
      return;
    const comment = `via obsidian file ${file.basename}: ${task.line.trim()}`;
    const requestId = `obsidian-tasks:${syncKey}`.slice(0, 250);
    try {
      const datapointId = await this.api.createDatapoint(
        this.settings.username,
        task.goalSlug,
        { value: task.value, comment, requestid: requestId }
      );
      this.settings.syncedDatapoints[syncKey] = {
        goalSlug: task.goalSlug,
        datapointId,
        requestId
      };
      await this.saveSettings();
      if (this.settings.showNotifications) {
        new import_obsidian3.Notice(`\u{1F41D} Synced +${task.value} to ${task.goalSlug}`);
      }
    } catch (e) {
      const msg = e instanceof Error ? e.message : "Unknown error";
      new import_obsidian3.Notice(`\u{1F41D} Sync failed: ${msg}`);
      console.error("Beeminder sync failed", { error: e, file: file.path, task });
    }
  }
  async undoTaskCompletion(file, task) {
    if (!this.settings.username || !task.goalSlug)
      return;
    const syncKey = this.buildSyncKey(file.path, task.lineNumber, task.line);
    const synced = this.settings.syncedDatapoints[syncKey];
    if (!synced)
      return;
    try {
      await this.api.deleteDatapoint(this.settings.username, synced.goalSlug, synced.datapointId);
      delete this.settings.syncedDatapoints[syncKey];
      await this.saveSettings();
      if (this.settings.showNotifications) {
        new import_obsidian3.Notice(`\u{1F41D} Removed datapoint from ${synced.goalSlug}`);
      }
    } catch (e) {
      const msg = e instanceof Error ? e.message : "Unknown error";
      new import_obsidian3.Notice(`\u{1F41D} Undo failed: ${msg}`);
      console.error("Beeminder undo failed", { error: e, file: file.path, task });
    }
  }
  // --- Sync key management ---
  buildSyncKey(filePath, lineNumber, line) {
    return JSON.stringify({ filePath, lineNumber, line });
  }
  parseSyncKey(key) {
    try {
      const p = JSON.parse(key);
      if (typeof p.filePath === "string" && typeof p.lineNumber === "number" && typeof p.line === "string") {
        return p;
      }
      return null;
    } catch (e) {
      return null;
    }
  }
  async migrateSyncKeysForMovedTasks(filePath, previousSnapshot, currentSnapshot) {
    var _a;
    const previousByIdentity = /* @__PURE__ */ new Map();
    const previousTasks = Array.from(previousSnapshot.tasks.values());
    const currentTasks = Array.from(currentSnapshot.tasks.values());
    for (const task of previousTasks) {
      const identity = buildTaskIdentity(task);
      const matches = (_a = previousByIdentity.get(identity)) != null ? _a : [];
      matches.push(task);
      previousByIdentity.set(identity, matches);
    }
    const matchedPreviousTasks = /* @__PURE__ */ new Set();
    const matchedCurrentTasks = /* @__PURE__ */ new Set();
    let changed = false;
    const migrated = { ...this.settings.syncedDatapoints };
    for (const currentTask of currentTasks) {
      const identity = buildTaskIdentity(currentTask);
      const matches = previousByIdentity.get(identity);
      if (!(matches == null ? void 0 : matches.length))
        continue;
      const previousTask = matches.shift();
      matchedPreviousTasks.add(previousTask);
      matchedCurrentTasks.add(currentTask);
      if (previousTask.lineNumber === currentTask.lineNumber)
        continue;
      const oldKey = this.buildSyncKey(filePath, previousTask.lineNumber, previousTask.line);
      const newKey = this.buildSyncKey(filePath, currentTask.lineNumber, currentTask.line);
      const synced = migrated[oldKey];
      if (!synced || migrated[newKey])
        continue;
      migrated[newKey] = {
        ...synced,
        requestId: `obsidian-tasks:${newKey}`.slice(0, 250)
      };
      delete migrated[oldKey];
      changed = true;
    }
    if (changed) {
      this.settings.syncedDatapoints = migrated;
      await this.saveSettings();
    }
    return {
      unmatchedPreviousTasks: previousTasks.filter((task) => !matchedPreviousTasks.has(task)),
      unmatchedCurrentTasks: currentTasks.filter((task) => !matchedCurrentTasks.has(task))
    };
  }
  async migrateSyncKeysForRename(oldPath, newPath) {
    let changed = false;
    const migrated = {};
    for (const [key, value] of Object.entries(this.settings.syncedDatapoints)) {
      const parsed = this.parseSyncKey(key);
      if ((parsed == null ? void 0 : parsed.filePath) === oldPath) {
        const newKey = this.buildSyncKey(newPath, parsed.lineNumber, parsed.line);
        migrated[newKey] = { ...value, requestId: `obsidian-tasks:${newKey}`.slice(0, 250) };
        changed = true;
      } else {
        migrated[key] = value;
      }
    }
    if (changed) {
      this.settings.syncedDatapoints = migrated;
      await this.saveSettings();
    }
  }
  async removeSyncKeysForFile(filePath) {
    let changed = false;
    const remaining = {};
    for (const [key, value] of Object.entries(this.settings.syncedDatapoints)) {
      const parsed = this.parseSyncKey(key);
      if ((parsed == null ? void 0 : parsed.filePath) === filePath) {
        changed = true;
      } else {
        remaining[key] = value;
      }
    }
    if (changed) {
      this.settings.syncedDatapoints = remaining;
      await this.saveSettings();
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    if (!Number.isInteger(this.settings.autocompleteMinMatchLength) || this.settings.autocompleteMinMatchLength < 0) {
      this.settings.autocompleteMinMatchLength = DEFAULT_SETTINGS.autocompleteMinMatchLength;
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var BeeminderSyncSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian3.Setting(containerEl).setName("Auth token").setDesc("Stored in Obsidian secret storage when available.").addText((text) => {
      text.setPlaceholder("Paste your Beeminder auth token");
      text.onChange(async (value) => {
        if (!value.trim())
          return;
        await this.plugin.storeToken(value.trim());
        text.setValue("");
        new import_obsidian3.Notice("Token saved.");
      });
    }).addButton((btn) => {
      btn.setButtonText("Clear").onClick(async () => {
        await this.plugin.clearToken();
        new import_obsidian3.Notice("Token cleared.");
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Username").setDesc("Auto-filled after token validation.").addText(
      (text) => text.setPlaceholder("username").setValue(this.plugin.settings.username).onChange(async (value) => {
        this.plugin.settings.username = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Validate token & refresh goals").setDesc("Checks the token and caches your goal list for autocomplete.").addButton((btn) => {
      btn.setButtonText("Validate").setCta().onClick(async () => {
        btn.setDisabled(true);
        try {
          await this.plugin.validateAndRefreshGoals();
          new import_obsidian3.Notice(`Connected as ${this.plugin.settings.username} (${this.plugin.settings.cachedGoals.length} goals)`);
          this.display();
        } catch (e) {
          new import_obsidian3.Notice(e instanceof Error ? e.message : "Validation failed.");
        } finally {
          btn.setDisabled(false);
        }
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Autocomplete minimum match length").setDesc("How many typed characters are required before text-based goal suggestions appear. Set to 0 to show suggestions immediately on task lines.").addText(
      (text) => text.setPlaceholder("1").setValue(String(this.plugin.settings.autocompleteMinMatchLength)).onChange(async (value) => {
        const parsed = Number.parseInt(value, 10);
        this.plugin.settings.autocompleteMinMatchLength = Number.isInteger(parsed) && parsed >= 0 ? parsed : DEFAULT_SETTINGS.autocompleteMinMatchLength;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Show notifications").setDesc("Show a notice when datapoints are synced or removed.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showNotifications).onChange(async (value) => {
        this.plugin.settings.showNotifications = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Open Beeminder").setDesc("Get your auth token from Beeminder.").addButton((btn) => {
      btn.setButtonText("Open").onClick(() => {
        window.open("https://www.beeminder.com/api/v1/auth_token.json", "_blank", "noopener,noreferrer");
      });
    });
    containerEl.createEl("h3", { text: "Usage" });
    const instructions = containerEl.createDiv({ cls: "beeminder-settings-help" });
    for (const tip of USAGE_TIPS) {
      const tipEl = instructions.createDiv({ cls: "beeminder-settings-help-tip" });
      tipEl.createEl("strong", { text: tip.title });
      tipEl.createEl("p", { text: tip.body });
      if (tip.code) {
        tipEl.createEl("code", { text: tip.code });
      }
    }
  }
};
